### ISSUE TITLE
AttributeError: 'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by harrr1** [hustille/ComfyUI_Fooocus_KSampler#12]
I was unable to fix this, however reverting 1c012d69afa8bd92a007a3e468e2a1f874365d39 in ComfyUI solves the problem (for now).

```
  File "ComfyUI/custom_nodes/ComfyUI_Fooocus_KSampler/sampler/Fooocus/patch.
py", line 365, in sampling_function_patched
    cond, uncond = calc_cond_uncond_batch(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "ComfyUI/custom_nodes/ComfyUI_Fooocus_KSampler/sampler/Fooocus/patch.py", line 316, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, **c).chunk(batch_chunks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ComfyUI/comfy/model_base.py", line 63, in apply_model
    context = context.to(dtype)
              ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'to'
```

**Comment by VisualFox** [comment]
FYI: open issue on ComfyUI: https://github.com/comfyanonymous/ComfyUI/issues/1385

**Comment by alexbofa** [comment]
same
